var config={
	resSrcList:{
		down:{
			type:"img",
			src:"img/iconfont-down.png"
		},
		/*downleft:{
			type:"img",
			src:"img/iconfont-downleft.png"
		},
		downright:{
			type:"img",
			src:"img/iconfont-downright.png"
		},*/
		up:{
			type:"img",
			src:"img/iconfont-up.png"
		},
		/*upleft:{
			type:"img",
			src:"img/iconfont-upleft.png"
		},
		upright:{
			type:"img",
			src:"img/iconfont-upright.png"
		},*/
		left:{
			type:"img",
			src:"img/iconfont-left.png"
		},
		right:{
			type:"img",
			src:"img/iconfont-right.png"
		}
	},
	
	dev_width:460,
	dev_height:780
}
